#!/bin/bash

##
## General
##

export EDITOR=vim


##
## Path
##

if [ -d ~/.local/bin ]; then
    PATH=$PATH:~/.local/bin
fi

export PATH=$PATH:.:~/.zmenv/scripts/

##
## Work Exports
##

export EPOCH=~/coffee/src/lib/epochlabs


##
## Languages
##

# Go
if [ -e "/usr/local/go" ] ; then
  export GOPATH=~/go
  mkdir -p $GOPATH
  export GOROOT=/usr/local/go
  export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
fi

# Rust
if [ -d "$HOME/.multirust" ] ; then
  export PATH=$PATH:"/home/zach/.multirust/toolchains/nightly/cargo/bin"
  export PATH=$PATH:"/home/zach/.multirust/toolchains/stable/cargo/bin"
fi
