#!/bin/bash

##
## General
##

export EDITOR=vim


##
## Path
##

if [ -d ~/.local/bin ]; then
    PATH=$PATH:~/.local/bin
fi

if [ -d ~/.local/bin/clion ]; then
    PATH=$PATH:~/.local/bin/clion/bin
fi

export PATH=$PATH:.:~/.zmenv/scripts/

##
## Work Exports
##

export EPOCH=~/coffee/src/lib/epochlabs


##
## Languages
##

# Go
if [ -e "/usr/local/go" ] ; then
  mkdir -p ~/go
  export GOPATH=~/go
  export GOROOT=/usr/local/go
  export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
fi
