#!/bin/zsh

LOCKIMAGE=/tmp/lockimage
NASA_KEY="Nj8LCWAEmBJzKgdAzGNzoHhldasalCHWk4OEUN19"
NASA_URL="https://api.nasa.gov/planetary/apod?concept_tags=False&hd=True&api_key=$NASA_KEY"

lock() {
    #curl -s $NASA_URL | jq .url | xargs wget -O $LOCKIMAGE.jpg
    #convert $LOCKIMAGE.jpg $LOCKIMAGE.png
    #i3lock -i $LOCKIMAGE.png
    /bin/lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        #lock && systemctl suspend
		lock && pm-suspend
        ;;
    hibernate)
        #lock && systemctl hibernate
		pm-hibernate 
        ;;
    reboot)
        #systemctl reboot
		reboot
        ;;
    shutdown)
        #systemctl poweroff
		shutdown
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
